# =========================
# AcademicPages 基础配置
# =========================
title: "Minghao Dang, Ph.D."
name: "Minghao (M.) Dang"
tagline: "Single-cell multi-omics · Tumor microenvironment · Multiple myeloma"
description: "Computational biologist at MD Anderson Cancer Center. Focused on single-cell multi-omics, tumor heterogeneity, and TME dynamics in blood cancers."

# 站点与部署
url: "https://MDangLab.github.io"   # ← 改为你的 GitHub Pages 主域名
baseurl: ""                                 # 通常留空（根目录部署）
repository: "MDangLab/MDangLab.github.io"

# 作者信息（页面侧边栏 & 结构化数据）
author:
  name: "Minghao Dang"
  avatar: "images/profile.jpg"              # 上传头像到 images/ 并修改文件名
  bio: "Fellow & Associate Data Scientist, Department of Lymphoma/Myeloma, MD Anderson Cancer Center."
  location: "Houston, TX, USA"
  employer: "UT MD Anderson Cancer Center"
  email: "<minghao.dang@hotmail.com>"            # 用于联系按钮与结构化数据
  uri: "https://MDangLab.github.io"  # 你的主页 URL
  # 社交/学术账户（按需填写）
  github: "<your-username>"
  google_scholar: "https://scholar.google.com/citations?user=<your-id>"
  orcid: "https://orcid.org/<your-orcid>"
  twitter: ""
  linkedin: "https://www.linkedin.com/in/<your-id>/"
  researchgate: "https://www.researchgate.net/profile/<your-id>"
  semanticscholar: ""
  publons: ""
  wechat: ""                                # 可留空
  # 研究兴趣（用于 about 页/侧边栏展示，部分主题会读取）
  interests:
    - Single-cell multi-omics
    - Tumor microenvironment
    - Multiple myeloma
    - Spatial transcriptomics

# 站点外观与主题
#remote_theme: "academicpages/academicpages" # 使用 AcademicPages 远程主题
permalink: /:categories/:title/
paginate: 5
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# 时区与语言
timezone: "America/Chicago"
lang: "en"

# 菜单导航（也可在 _data/navigation.yml 中细化）
navigation:
  - title: "Home"
    url: /
  - title: "Publications"
    url: /publications/
  - title: "Research"
    url: /research/
  - title: "Talks"
    url: /talks/
  - title: "Teaching"
    url: /teaching/
  - title: "CV"
    url: /cv/
  - title: "Contact"
    url: /contact/

# 集合（Collections）
collections:
  publications:
    output: true
    permalink: /publications/:path/
  talks:
    output: true
    permalink: /talks/:path/
  teaching:
    output: true
    permalink: /teaching/:path/
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# 插件（GitHub Pages 允许的官方插件）
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jemoji

# SEO/统计（按需开启）
google_analytics: ""                        # 填 UA- 或 G- 开头的 ID；不需要可留空
google_site_verification: ""                # 搜索控制台验证可填
bing_site_verification: ""

# 版权与页脚
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/<your-username>"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=<your-id>"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/<your-orcid>"

# 构建排除（无需部署的目录/文件）
exclude:
  - README.md
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json

# 可选：bibtex 与发表列表（如果用到）
scholar:
  style: apa
  locale: en
  source: ./_bibliography
  bibliography: papers.bib
  bibliography_template: bibtex.html
  sort_by: year,month
  order: descending

# 图片与资源的路径（可按需调整）
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author_profile: true
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
      author_profile: true
  - scope:
      path: ""
      type: "talks"
    values:
      layout: "talk"
      author_profile: true
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      author_profile: true
